name: line_duty
description: Line Duty - draw routes, keep the flows apart (internal name line_duty)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0"
  flutter: ">=3.27.0"

dependencies:
  domain:
    path: ./domain
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  data:
    path: ./data
  navigation:
    path: ./navigation
  features:
    path: ./features

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flame: ^1.38.0

flutter:
  uses-material-design: true

  assets:
    - core/resources/audio/
    - core/resources/fonts/OFL-GolosText.txt
    - core/resources/fonts/OFL-Unbounded.txt
  fonts:
    - family: GolosText
      fonts:
        - asset: core/resources/fonts/GolosText[wght].ttf
    - family: Unbounded
      fonts:
        - asset: core/resources/fonts/Unbounded[wght].ttf
